namespace SchoolManagement.Domain.Security;

/// <summary>
/// Spec 4.5's six seeded roles: fixed, documented identifiers (a fresh install and an existing
/// database must agree on them forever — a future <c>role_assignment</c> row references a role by
/// this id, per TASK-0030) and each role's canonical, alias-resolved privilege set, hand-transcribed
/// from spec 4.5's prose against <see cref="PrivilegeRegistry"/> — the same way
/// <see cref="PrivilegeRegistry"/> itself is hand-transcribed from spec 4.4, rather than generated by
/// a wildcard-expansion routine that this file and its own pinning test could then both call and
/// silently agree with for the wrong reason.
/// </summary>
/// <remarks>
/// <para>
/// Consumed by <c>RoleConfiguration</c>'s EF Core <c>HasData</c> seed (TASK-0028 dispatch 3) and by
/// <c>ApiTestFixture</c>'s post-<c>TRUNCATE</c> reseed, which must reproduce the migration's seed data
/// exactly — the same relationship <c>SchoolProfile.SingletonId</c> already has with
/// <c>ReseedSchoolProfileAsync</c>.
/// </para>
/// <para>
/// <b>Three disagreements between spec 4.5 (this file's source) and spec 4.4's per-privilege
/// "Seeded to" column were found while transcribing, and are disclosed rather than silently
/// reconciled</b> (full detail: <c>backend/docs/ASSUMPTIONS.md</c> §2.21): spec 4.4 lists School
/// Administrator against <c>weekly.enter</c> and <c>weekly.publish</c>, and marks <c>weekly.view</c>
/// "all roles" (which would include both School Administrator and Auditor), and marks
/// <c>subject.view</c> "all roles" (which would include Bursar) — yet spec 4.5's own prose for School
/// Administrator names no <c>weekly.*</c> privilege at all, its prose for Auditor omits
/// <c>weekly.view</c>, and its prose for Bursar omits <c>subject.view</c>. Spec 4.5 — the section
/// this dispatch was named to implement, with 4.4 described as only "the vocabulary it draws on" — is
/// treated as authoritative in every case below; the conflict is recorded for the orchestrator/human
/// to confirm or overrule, not chosen silently.
/// </para>
/// <para>
/// One more note the task card raised and this transcription checked directly: <c>pupil.delete</c>
/// DOES exist in the register (spec 4.4.4, seeded to Super Admin only) and in
/// <see cref="Privileges.Pupil.Delete"/> — School Administrator's "except delete" excludes a real,
/// existing code, not an invented one.
/// </para>
/// </remarks>
public static class SeededRoles
{
    /// <summary>Fixed, documented role ids. Never regenerate — an existing database depends on these.</summary>
    public static readonly Guid SuperAdminId = new("00000000-0000-0000-0000-000000000101");

    /// <inheritdoc cref="SuperAdminId"/>
    public static readonly Guid SchoolAdministratorId = new("00000000-0000-0000-0000-000000000102");

    /// <inheritdoc cref="SuperAdminId"/>
    public static readonly Guid HeadTeacherId = new("00000000-0000-0000-0000-000000000103");

    /// <inheritdoc cref="SuperAdminId"/>
    public static readonly Guid ClassTeacherId = new("00000000-0000-0000-0000-000000000104");

    /// <inheritdoc cref="SuperAdminId"/>
    public static readonly Guid BursarId = new("00000000-0000-0000-0000-000000000105");

    /// <inheritdoc cref="SuperAdminId"/>
    public static readonly Guid AuditorId = new("00000000-0000-0000-0000-000000000106");

    /// <summary>
    /// Fixed concurrency-token seed values, one per role (TASK-0028 dispatch 2's
    /// <c>AuditingInterceptor</c> reassigns this on the first real save; these are only the seed's
    /// starting values, and must be literal constants — <c>Guid.CreateVersion7()</c> would mint a new
    /// value every time the model is built, which is every process start, making the migration's own
    /// seed data differ from the running model and falsely look like a pending migration).
    /// </summary>
    private static readonly Guid SuperAdminVersion = new("00000000-0000-0000-0000-000000000201");
    private static readonly Guid SchoolAdministratorVersion = new("00000000-0000-0000-0000-000000000202");
    private static readonly Guid HeadTeacherVersion = new("00000000-0000-0000-0000-000000000203");
    private static readonly Guid ClassTeacherVersion = new("00000000-0000-0000-0000-000000000204");
    private static readonly Guid BursarVersion = new("00000000-0000-0000-0000-000000000205");
    private static readonly Guid AuditorVersion = new("00000000-0000-0000-0000-000000000206");

    /// <summary>
    /// Sentinel "installed, not a real event" timestamp for every seed row's <c>CreatedAtUtc</c> —
    /// same convention as <c>SchoolProfileConfiguration</c>'s version pointers starting at 0. Fixed
    /// for the same reason the Version tokens above are: it is baked into a migration.
    /// </summary>
    public static readonly DateTimeOffset SeedTimestamp = DateTimeOffset.UnixEpoch;

    /// <summary>"Every privilege in the register. Not editable." (spec 4.5).</summary>
    public static readonly IReadOnlyList<string> SuperAdminPrivileges =
        PrivilegeRegistry.All
            .Select(definition => definition.Code)
            .OrderBy(code => code, StringComparer.Ordinal)
            .ToArray();

    /// <summary>
    /// School Administrator (spec 4.5): "All of <c>session.*</c>, <c>level.* except delete</c>,
    /// <c>arm.* except delete</c>, <c>pupil.* except delete and regnumber.correct</c>,
    /// <c>guardian.*</c>, <c>subject.* except delete</c>, <c>promotion.run</c>,
    /// <c>role.scope.assign</c>, <c>admin.view</c>, <c>settings.view</c>, <c>pin.view</c>,
    /// <c>pin.usage.view</c>, <c>result.view</c>, <c>result.print</c>, <c>report.*</c>." 43 codes.
    /// <c>guardian.*</c> resolves through <see cref="PrivilegeAliases"/> to its three
    /// <c>contact.*</c> replacements (<c>create</c>/<c>update</c>/<c>view</c> — the only three that
    /// ever existed under the old name) — no <c>guardian.*</c> code is ever stored. NOT
    /// <c>weekly.*</c> — see the class remarks.
    /// </summary>
    public static readonly IReadOnlyList<string> SchoolAdministratorPrivileges = Sorted(
    [
        // session.*
        Privileges.Session.View, Privileges.Session.Create, Privileges.Session.Update,

        // level.* except delete
        Privileges.Level.View, Privileges.Level.Create, Privileges.Level.Update, Privileges.Level.Deactivate,

        // arm.* except delete
        Privileges.Arm.View, Privileges.Arm.Create, Privileges.Arm.Update, Privileges.Arm.FormTeacherAssign,
        Privileges.Arm.CapacityOverride,

        // pupil.* except delete and regnumber.correct
        Privileges.Pupil.View, Privileges.Pupil.Create, Privileges.Pupil.Update, Privileges.Pupil.PhotoUpdate,
        Privileges.Pupil.StatusUpdate, Privileges.Pupil.Transfer, Privileges.Pupil.Import,
        Privileges.Pupil.AdmissionApprove, Privileges.Pupil.SafeguardingView, Privileges.Pupil.SafeguardingUpdate,
        Privileges.Pupil.DocumentManage,

        // guardian.* — resolved via PrivilegeAliases to its three contact.* replacements
        Privileges.Contact.Create, Privileges.Contact.Update, Privileges.Contact.View,

        // subject.* except delete
        Privileges.Subject.View, Privileges.Subject.Create, Privileges.Subject.Update,
        Privileges.Subject.Deactivate, Privileges.Subject.Map, Privileges.Subject.MapArm,
        Privileges.Subject.Unmap,

        // named individually
        Privileges.Promotion.Run, Privileges.Role.ScopeAssign, Privileges.Admin.View,
        Privileges.Settings.View, Privileges.Pin.View, Privileges.Pin.UsageView, Privileges.Results.View,
        Privileges.Results.Print,

        // report.*
        Privileges.Report.View, Privileges.Report.Export,
    ]);

    /// <summary>
    /// Head Teacher (spec 4.5): "<c>result.view</c>, <c>result.compute</c>,
    /// <c>result.remark.headteacher</c>, <c>result.approve</c>, <c>result.return</c>,
    /// <c>result.publish</c>, <c>result.annual.compute</c>, <c>result.print</c>,
    /// <c>promotion.decide</c>, <c>pupil.view</c>, <c>contact.view</c>,
    /// <c>pupil.safeguarding.view</c>, <c>pupil.safeguarding.update</c>,
    /// <c>pupil.admission.approve</c>, <c>weekly.view</c>, <c>weekly.enter</c>, <c>weekly.publish</c>,
    /// <c>arm.view</c>, <c>subject.view</c>, <c>session.view</c>, <c>level.view</c>,
    /// <c>settings.view</c>, <c>pin.view</c>, <c>report.*</c>." 25 codes.
    /// </summary>
    public static readonly IReadOnlyList<string> HeadTeacherPrivileges = Sorted(
    [
        Privileges.Results.View, Privileges.Results.Compute, Privileges.Results.RemarkHeadTeacher,
        Privileges.Results.Approve, Privileges.Results.Return, Privileges.Results.Publish,
        Privileges.Results.AnnualCompute, Privileges.Results.Print, Privileges.Promotion.Decide,
        Privileges.Pupil.View, Privileges.Contact.View, Privileges.Pupil.SafeguardingView,
        Privileges.Pupil.SafeguardingUpdate, Privileges.Pupil.AdmissionApprove,
        Privileges.Weekly.View, Privileges.Weekly.Enter, Privileges.Weekly.Publish,
        Privileges.Arm.View, Privileges.Subject.View, Privileges.Session.View, Privileges.Level.View,
        Privileges.Settings.View, Privileges.Pin.View,

        // report.*
        Privileges.Report.View, Privileges.Report.Export,
    ]);

    /// <summary>
    /// Class Teacher (spec 4.5; arm-scoped by the assignment that will hold this role — TASK-0030,
    /// this row has no scope of its own): "<c>result.view</c>, <c>result.score.enter</c>,
    /// <c>result.trait.enter</c>, <c>result.attendance.enter</c>, <c>result.remark.classteacher</c>,
    /// <c>result.compute</c>, <c>result.submit</c>, <c>result.print</c>, <c>pupil.view</c>,
    /// <c>pupil.photo.update</c>, <c>contact.view</c>, <c>pupil.safeguarding.view</c>,
    /// <c>weekly.view</c>, <c>weekly.enter</c>, <c>weekly.publish</c>, <c>arm.view</c>,
    /// <c>subject.view</c>, <c>session.view</c>, <c>level.view</c>." 19 codes.
    /// </summary>
    public static readonly IReadOnlyList<string> ClassTeacherPrivileges = Sorted(
    [
        Privileges.Results.View, Privileges.Results.ScoreEnter, Privileges.Results.TraitEnter,
        Privileges.Results.AttendanceEnter, Privileges.Results.RemarkClassTeacher, Privileges.Results.Compute,
        Privileges.Results.Submit, Privileges.Results.Print,
        Privileges.Pupil.View, Privileges.Pupil.PhotoUpdate, Privileges.Contact.View,
        Privileges.Pupil.SafeguardingView,
        Privileges.Weekly.View, Privileges.Weekly.Enter, Privileges.Weekly.Publish,
        Privileges.Arm.View, Privileges.Subject.View, Privileges.Session.View, Privileges.Level.View,
    ]);

    /// <summary>
    /// Bursar (spec 4.5): "<c>pin.view</c>, <c>pin.generate</c>, <c>pin.print</c>,
    /// <c>pin.revoke</c>, <c>pin.usage.view</c>, <c>pupil.view</c>, <c>contact.view</c>,
    /// <c>weekly.view</c>, <c>arm.view</c>, <c>session.view</c>, <c>level.view</c>. No result
    /// privilege of any kind, and no safeguarding privilege: a bursar has no reason to read a
    /// child's allergy list." 11 codes. NOT <c>subject.view</c> — see the class remarks.
    /// </summary>
    public static readonly IReadOnlyList<string> BursarPrivileges = Sorted(
    [
        Privileges.Pin.View, Privileges.Pin.Generate, Privileges.Pin.Print, Privileges.Pin.Revoke,
        Privileges.Pin.UsageView,
        Privileges.Pupil.View, Privileges.Contact.View, Privileges.Weekly.View,
        Privileges.Arm.View, Privileges.Session.View, Privileges.Level.View,
    ]);

    /// <summary>
    /// Auditor (spec 4.5): "<c>audit.view</c>, <c>audit.export</c>, <c>settings.view</c>,
    /// <c>admin.view</c>, <c>role.view</c>, <c>session.view</c>, <c>level.view</c>, <c>arm.view</c>,
    /// <c>subject.view</c>, <c>pupil.view</c>, <c>result.view</c>, <c>pin.view</c>,
    /// <c>pin.usage.view</c>, <c>report.*</c>. No write privilege." 15 codes. NOT
    /// <c>weekly.view</c> — see the class remarks.
    /// </summary>
    public static readonly IReadOnlyList<string> AuditorPrivileges = Sorted(
    [
        Privileges.Audit.View, Privileges.Audit.Export, Privileges.Settings.View, Privileges.Admin.View,
        Privileges.Role.View, Privileges.Session.View, Privileges.Level.View, Privileges.Arm.View,
        Privileges.Subject.View, Privileges.Pupil.View, Privileges.Results.View, Privileges.Pin.View,
        Privileges.Pin.UsageView,

        // report.*
        Privileges.Report.View, Privileges.Report.Export,
    ]);

    /// <summary>
    /// De-duplicates and orders codes ordinally — the same normalisation <see cref="Role"/>'s
    /// private <c>TryNormalizePrivileges</c> applies, kept consistent here even though
    /// <c>HasData</c> bypasses that factory entirely.
    /// </summary>
    private static string[] Sorted(string[] codes) =>
        codes.Distinct(StringComparer.Ordinal).OrderBy(code => code, StringComparer.Ordinal).ToArray();

    /// <summary>
    /// All six seeded roles, in spec 4.5's own table order (Super Admin first) — the SINGLE source
    /// both <c>RoleConfiguration</c>'s <c>HasData</c> seed and <c>ApiTestFixture</c>'s post-
    /// <c>TRUNCATE</c> reseed are built from, so the row each writes can never drift from the other.
    /// </summary>
    public static readonly IReadOnlyList<SeededRoleDefinition> All =
    [
        new(
            SuperAdminId,
            Role.ReservedName,
            "Holds every privilege school-wide. Creates other admins, builds roles, edits settings.",
            IsSystem: true,
            SuperAdminPrivileges,
            SuperAdminVersion),
        new(
            SchoolAdministratorId,
            "School Administrator",
            "Runs the school's records: sessions, terms, levels, arms, subjects, pupils, guardians, promotion.",
            IsSystem: false,
            SchoolAdministratorPrivileges,
            SchoolAdministratorVersion),
        new(
            HeadTeacherId,
            "Head Teacher",
            "Reviews computed results for an arm, writes the head teacher's remark, approves or returns, publishes.",
            IsSystem: false,
            HeadTeacherPrivileges,
            HeadTeacherVersion),
        new(
            ClassTeacherId,
            "Class Teacher",
            "Enters continuous assessment and examination marks, trait ratings, attendance figures and the class teacher's remark, for the arms their assignment is scoped to.",
            IsSystem: false,
            ClassTeacherPrivileges,
            ClassTeacherVersion),
        new(
            BursarId,
            "Bursar",
            "Generates, prints, revokes and reports on access pins. Reads the pupil register. Cannot see or enter marks.",
            IsSystem: false,
            BursarPrivileges,
            BursarVersion),
        new(
            AuditorId,
            "Auditor",
            "Read-only across records, results and the audit log. Holds no write privilege at all.",
            IsSystem: false,
            AuditorPrivileges,
            AuditorVersion),
    ];
}

/// <summary>
/// One <see cref="SeededRoles"/> row — a top-level type (not nested in the static class) per CA1034.
/// </summary>
public sealed record SeededRoleDefinition(
    Guid Id,
    string Name,
    string? Description,
    bool IsSystem,
    IReadOnlyList<string> Privileges,
    Guid Version);
