namespace SchoolManagement.Api.Configuration;

/// <summary>
/// Distinguishes a real run from a run that exists only to emit the OpenAPI document.
/// </summary>
/// <remarks>
/// <para>
/// THE PROBLEM THIS SOLVES. The OpenAPI document is generated by STARTING the application and asking
/// it to describe its endpoints — that is how the tooling reads route metadata, and it is what makes
/// the document impossible to fake. But this service also validates its configuration at startup
/// (<c>ValidateOnStart</c>) and refuses to run without a database connection string. Those two
/// requirements collide: producing a document would otherwise need a configured database and a chosen
/// identity provider, so a release operator could not regenerate the contract without provisioning
/// infrastructure, and no developer could run <c>dotnet build</c> without a database.
/// </para>
/// <para>
/// WHY NOT JUST SUPPLY A DUMMY CONNECTION STRING. That is the obvious shortcut and it is a trap: a
/// realistic-looking placeholder credential in a build script is exactly the kind of value that gets
/// copied into a deployment and quietly works. This flag is instead explicit about what it is —
/// nothing is pretended to be configured, the checks that need live infrastructure are simply not
/// registered, and the process never opens a connection.
/// </para>
/// <para>
/// SAFETY. This mode only ever SKIPS startup validation; it never relaxes authentication,
/// authorisation or any request-path behaviour, and the process is terminated by the tooling before it
/// serves a request. Set only by the documented contract-generation command — never in a deployment.
/// </para>
/// </remarks>
public static class HostMode
{
    /// <summary>Configuration key (and environment variable name) enabling contract-generation mode.</summary>
    public const string ContractGenerationKey = "SCHOOLMANAGEMENT_CONTRACT_GENERATION";

    /// <summary>
    /// Whether this process was started solely to emit the OpenAPI document.
    /// </summary>
    /// <param name="configuration">The configuration to read the flag from.</param>
    public static bool IsContractGeneration(IConfiguration configuration)
    {
        ArgumentNullException.ThrowIfNull(configuration);

        return configuration.GetValue<bool>(ContractGenerationKey);
    }
}
